apiVersion: louhi/v2
kind: Flow
metadata:
  name: Build and Release
spec:
  sourceRepositoryName: functions-framework-nodejs
  environmentName: default
  pipeline:
    stages:
    - name: Build
      index: 1
      stageTypeName: Build
    - name: Release
      index: 2
      stageTypeName: Release
  triggers:
  - name: Tag Created Trigger
    type: tag-trigger
    parameters:
      repositoryName: functions-framework-nodejs
      tagRegularExpression: "^v[0-9]+[\\.0-9]*$"
