#!/bin/bash

# Generates package-lock.json files for package.json files for different
# function-to-app conversion scenarios. Created lock files should be committed
# and used in builds.

set -e

for dir in without-package with-package-without-framework with-package-with-framework; do
  rm ${dir}/package-lock.json
  npm --prefix ${dir} --package-lock-only --ignore-scripts install
  rm -rf ${dir}/functions
done
