#!/bin/bash

# Generates package-lock.json files for package.json files for different
# function-to-app conversion scenarios. Created lock files should be committed
# and used in builds.

set -e

for dir in without-package with-package-without-framework with-package-with-framework; do
  mkdir ${dir}/functions-framework
  cp ../package.json ${dir}/functions-framework/
  rm ${dir}/package-lock.json
  npm --prefix ${dir} --package-lock-only install
  rm -rf ${dir}/functions-framework
  rm -rf ${dir}/functions
done
