# Validates Functions Framework with GCF buildpacks.
name: Buildpack Integration Test
on:
  push:
    branches:
      - main
  pull_request:
  # Runs every day on 12:00 AM PST
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  nodejs10:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.4
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs10'
      builder-runtime-version: '10'
  nodejs12:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.4
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs12'
      builder-runtime-version: '12'
  nodejs14:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.4
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs14'
      builder-runtime-version: '14'
  nodejs16:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.4
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs16'
      builder-runtime-version: '16'
  nodejs18:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.4
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs18'
      builder-runtime-version: '18'
  nodejs20:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.4
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs20'
      builder-runtime-version: '20'
