# Validates Functions Framework with GCF buildpacks.
name: Buildpack Integration Test
on:
  push:
    branches:
      - master
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  nodejs10:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.0
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs10'
  nodejs12:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.0
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs12'
  nodejs14:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.0
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs14'
  nodejs16:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.0
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs16'
  nodejs18:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.0
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs18'
  nodejs20:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.8.0
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs20'
