# Validates Functions Framework with GCF buildpacks.
name: Buildpack Integration Test
on:
  push:
    branches:
      - main
  pull_request:
  # Runs every day on 12:00 AM PST
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  nodejs18:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@main
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs18'
      builder-runtime-version: '18'
      builder-url: 'us-docker.pkg.dev/serverless-runtimes/google-22-full/builder/nodejs:latest'
  nodejs20:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@main
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs20'
      builder-runtime-version: '20'
      builder-url: 'us-docker.pkg.dev/serverless-runtimes/google-22-full/builder/nodejs:latest'
  nodejs22:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@main
    with:
      http-builder-source: 'test/conformance'
      http-builder-target: 'writeHttpDeclarative'
      cloudevent-builder-source: 'test/conformance'
      cloudevent-builder-target: 'writeCloudEventDeclarative'
      prerun: 'test/conformance/prerun.sh'
      builder-runtime: 'nodejs22'
      builder-runtime-version: '22'
      builder-url: 'us-docker.pkg.dev/serverless-runtimes/google-22-full/builder/nodejs:latest'
